config/routes.rb
FirstApp::Application.routes.draw do
  resources :authors

  resources :items do
	 collection do
		post "move_to_start"
		post "move_to_end"
	 end
   end
  
  	root :to => "items#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name
  
  validates_presence_of :name
  
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :author_id, :name, :import_value
  
  validates_presence_of :name
  
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  def index
    @items = Item.all

    respond_to do |format|
      format.html
    end
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # GET /items/new
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /items/1
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /items/1
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
    end
  end
  
  
  def move_to_start
	@item = Item.find(params[:id])
	move_to_start(@item.id)
	
	respond_to do |format|
		format.html { redirect_to items_url }
	end
  end
  
  def move_to_end
	@item = Item.find(params[:id])
	move_to_end(@item.id)
	
	respond_to do |format|
		format.html { redirect_to items_url }
	end
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	
	
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

	def importance_order(arr)
		arr.each do |a|
			if a.import_value == nil
				a.import_value = 100
			end
		end
		arr.sort_by!{ |a| a.import_value }
		return arr
	end

	def move_to_start(id)
		im = Item.all
		im = importance_order(im)
		t = im.delete(Item.find(id))
		im.unshift(t)
		b = 1
		im.each do |x|
			x.import_value = b
			b+=1
		end
	end
	
	def move_to_end(id)
		im = Item.all
		im = importance_order(im)
		t = im.delete(Item.find(id))
		im.push(t)
		b = 1
		im.each do |x|
			x.import_value = b
			b+=1
		end
	end
	

end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Complete Author Listing</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>
<%= link_to 'New Item', new_item_path %>
<%= link_to 'Items', items_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @author.name %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br />
    <%= f.select(:author_id, options_from_collection_for_select(Author.all, :id, :name)) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1> To-do List </h1>

<div id= main_list_table>
	<table>
		<tr>
			<th> Item </th>
			<th> Author </th>
			<th></th>
			<th></th>
			<!--<th></th>
			<th></th>-->
		</tr>
		
<% order = importance_order(@items) %>
<% order.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= Author.find(item.author_id).name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
	<!-- Potential functionally to order the To-Do List based on importance.
				<td><%= link_to 'Move to start', item, collection: :move_to_start %></td>
				<td><%= link_to 'Move to end', item, collection: :move_to_end %></td> -->
  </tr>
<% end %>
	</table>
</div>

<br>

<%= link_to 'New Author', new_author_path %>
<%= link_to 'New Item', new_item_path %>
<%= link_to 'Authors', authors_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Author:</b>
  <%= Author.find(@item.author_id).name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>To-Do List Application</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

	</body>
</html>